#!/bin/bash
#current version is 0.2

out_path=/tmp
dir_name=$(pwd | tr '/' '\n' | tail -n1 | tr ' ' '_')

coder_av=$(which avconv)
coder_ff=$(which ffmpeg)

IFS=$'\n'

if [[ $(ls *.flac 2>/dev/null) ]]
	then
		if [[ $coder_av || $coder_ff ]]
			then
				mkdir $out_path/$dir_name

					if [[ $coder_av ]]; then coder=$coder_av; else if [[ $coder_ff ]]; then coder=$coder_ff; else
					echo 'neither /usr/bin/avconv nor /usr/bin/ffmpeg found in your system!'; exit 1 ;fi ;fi
						
				for track in *.flac; 
				do
					< /dev/null $coder -i "$track" -qscale: 1 $out_path/$dir_name/"${track[@]/%flac/mp3}"
				done
		fi
	else 
		echo 'you have no any flac tracks in ' $(pwd)
fi

unset IFS
